### ISSUE TITLE
file accumulation strategy hooks

### ISSUE THREAD

**Issue by jordandgray** [truemerrill/mortuary#13]
I will be using this in a deployment. For stability sake, I restart my deployed container anytime my python code has an uncaught exception/error/crash. I intend to use mortuary to capture the mortuary pickle dump and save it to a persistent volume. I intend to keep the last n crashes, and I want to ensure each dump has a unique name. 

With no intervention in the published code, I would create a new context manager that incorporates the mortuary context manager and add my file naming and file managing logic there. Didn't know if you had a different strategy in mind. 

I like the simplicity of the current code, wondering if there's a pythonic way to support file naming and file managing schemes in the context of your context manager without significantly complicating the solution

**Comment by jordandgray** [comment]
thinking about this a bit more--one way to address my issue would be to create an arg that takes a callable, and mortuary calls the callable somewhere in the teardown logic of of the context manager. In a potential scenario, you'd call my callable at the tail end of `__exit__()` 

In that scenario, I think I'd likely leave mortuary to output it's default pickle dump file to its default location, and I'd have my callable go about its business of doing something useful with the pickle. That could be copying the file to a persistent volume (and maybe delete old pickles if I'm low on space or overrun with pickle dumps). But it could just as easily be a file transfer (to minio). It could also be an email, or a webhook elsewhere.

I think the bottom line is that I realized if I'm going to `with mortuary.context():` my code, I think I want to be able to `with mortunary.context(after=my_specific_cleanup_use_case_that_differs_every_time_callable)' 

That make sense?

**Comment by true-merrill** [comment]
I have a proposal that I think gets you what you are after with minimal changes to mortuary's model.  

Naming conventions for the dump file are somewhat arbitrary.  The library should not apply any restrictions on how it's users want to name their files.  Already in `0.1` mortuary lets the user set whatever dump file they want, provided that the filename is precisely known *at the time you enter the mortuary context*.

## An example

To show what I mean, consider the following.

```python
import os
import random
from pathlib import Path

import requests

import mortuary


def get_random_pokemon() -> str:
    pokedex = random.randint(1, 1000)
    res = requests.get(f"https://pokeapi.co/api/v2/pokemon/{pokedex}/")
    return res.json()["name"]


def get_current_pid() -> str:
    return str(os.getpid())


def get_dump_file() -> Path:
    filename = f"{get_random_pokemon()}-{get_current_pid()}.pkl"
    return Path.cwd() / filename


with mortuary.context(dump=get_dump_file()):
    print("Doing something risky!")
    1 / 0
```

In this example, the the dumpfile is in the format `{pokemon-name}-{process-pid}.pkl` and the filename for the dump is assigned as soon as we enter the mortuary context.  When I ran it on my machine it produced the dumpfile `leafeon-99341.pkl`, which apparently is a grass-type evolution of eevee.

## The problem

As you pointed out, there are limitations to  assigning the filename as soon as we enter the context:

- What if the filename depends on data which isn't known until the exception is thrown?  For example, the filename might use the timestamp when the exception was thrown, or the name of the exception itself.  
- What if we don't know that we actually want to write a dump file until the exception is thrown?

## Proposal

Users need a way to assign the dump filename at the time the exception is thrown.  You're correct that the best way to do this is to context accept an argument which is a callback function.   Here is what I propose to do:

- Declare a type alias for `TracebackPathCallbackFn` as follows.

```python
from pathlib import Path
from typing import Callable, Union

PathLike = Union[str, Path]

# Type for callback functions
TracebackPathCallbackFn = Union[
    Callable[[], Union[PathLike, None]],             # No arguments, returns PathLike or None
    Callable[[Exception], Union[PathLike, None]]     # Accepts the exception as an argument, returns PathLike or None
]
```

- Change the `context(dump)` argument to accept a `str`, `Path`, or a `TracebackPathCallbackFn`.  The docstring for `context` will be updated as follows.

```

    Args:
        dump (PathLike, TracebackPathCallbackFn, optional): the traceback dump file. If this
            argument is a Path or string it is treated as a the filename of the dump file.  If this
            argument is callable, it is evaluated when the exception is detected by the context
            manager.  The callback function must return the filename of the dump file or `None`
            if no dump file should be captured.  Defaults to "traceback-dump.pkl".
        log (PathLike, TracebackPathCallbackFn optional): the traceback log file. If this
            argument is a Path or string it is treated as a the filename of the log file.  If this
            argument is callable, it is evaluated when the exception is detected by the context
            manager.  The callback function must return the filename of the log file or `None`
            if no log file should be captured. If not provided, then no traceback log is created.
            Defaults to None.
```

Allowing these two arguments to be callbacks solves the following problems:

- Users are free to assign whatever naming convention they want to dump and log files.
- Users  have more control over when dumps are captured.  For example, if they only wanted one dump file they could use a callback like the following:

```python

def only_one(path: PathLike) -> TracebackPathCallbackFn:
    pth = Path(path)
    def callback() -> Union[Path, None]:
        if not pth.exists():
            pth.parent.makedir(parents=True, exist_ok=True)
            return pth
        return None
    return callback

my_callback_fn = only_one("there/shall/be/only/one.pkl")
```

The logic inside the callback function only gets triggered once the `mortuary.context` sees an error.  In this case, it will only return a path if the dump file doesn't exist already, otherwise it will return `None` and no dump will be taken.  Users can use whatever logic they want here.

## Timeline

Changes are pretty minimal on my side.  I can get this implemented and released tonight if this works for your use case.

**Comment by true-merrill** [comment]
Oh, and I also forgot to add that I like the idea of an `after` hook, which is a callable of the form

```
TracebackAfterCallbackFn = Callable[[Path],None]
```

which is triggered only after a dump is taken.  Note that if the user causes a separate exception somewhere in this callback, mortuary will not catch that exception.

**Comment by jordandgray** [comment]
this sounds like a great strategy!

thanks for your consideration

**Comment by true-merrill** [comment]
Enhancement has been completed and merged back to the develop branch.   I am planning on releasing 0.1.1 to pypi shortly.
